=== 17719543022/BoardingControl_Linux/SDK/bin/3rdSo/ChinaSafe/IDCARDS/IDCARD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XMLSpy v2009 sp1 (http://www.altova.com)-->
<!ELEMENT vecLine ((CLine+))>
<!ELEMENT vecDeriveUnit ((CDeriveUnit*))>
<!ELEMENT vecFlagFind ((CFlagFind*))>
<!ELEMENT vecRegion ((CRegion*))>
<!ELEMENT vecSubTemplate ((CSubTemplate*))>
<!ELEMENT vecRecogUnit ((CRecogUnit*))>
<!ELEMENT vecProcessMode ((CAutoProcess*))>
<!ELEMENT vecAutoProcess ((vecProcessMode*))>
<!ELEMENT vecProcessImage ((CProcessImage*))>
<!ELEMENT vecLineKeyWord ((CKeyWord*))>
<!ELEMENT vecImageLightType ((LIGHTTYPE+))>
<!ELEMENT vecAnchor ((CAnchor*))>
<!ELEMENT vecCLocateAnchor ((CLocateAnchor*))>
<!ELEMENT vecAnchorLocateInfo ((CAnchorLocateInfo*))>
<!ELEMENT vecCharRatio ((CCharRatio*))>
<!ELEMENT vecKernal ((CKernalInfo*))>
<!ELEMENT vecCLocateMethod ((CLocateMethod+))>
<!ELEMENT vecCReplaceChar ((CReplaceChar+))>
<!ELEMENT vecCInsertChar ((CInsertChar+))>
<!ELEMENT vecOutPutResult ((COutPutResult+))>
<!ELEMENT vecMergeUnit ((CMergeUnit*))>
<!ELEMENT CMergeUnit EMPTY>
<!ATTLIST CMergeUnit 
  nDestUnitIndex CDATA #REQUIRED
  nDestUnitType (1|2|3|4) #REQUIRED
  nSrcUnitIndex CDATA #REQUIRED
  nSrcUnitType  CDATA #REQUIRED
  strSrc        CDATA #REQUIRED
  strDest       CDATA #REQUIRED
  nProcessPos   CDATA #REQUIRED
  bMeet         CDATA #REQUIRED
  bSynchronous  CDATA #REQUIRED 
  nOperateType  CDATA #REQUIRED
  >
<!ELEMENT COutPutResult ((CFormatInfo?))>
<!ATTLIST COutPutResult
	nIndex CDATA #REQUIRED
	cellRecogType (0|1|2|3|4|5|6|7|8|9|10|11|13|12|14|15|16|17|18|19|20|21|22) #REQUIRED
	cellName CDATA #REQUIRED
	nOutputThreshold CDATA #REQUIRED
	nOutputNumber CDATA #REQUIRED
	bFormatResult (0|1)  #REQUIRED
	bMainField (0|1)  #IMPLIED 
	cellNameEng CDATA #IMPLIED
>
<!ELEMENT CFormatInfo ((vecCReplaceChar?))>
<!ATTLIST CFormatInfo
	strInFormat CDATA #REQUIRED
	strOutFormat CDATA #REQUIRED
	strDefault CDATA #REQUIRED
>
<!ELEMENT CReplaceChar EMPTY>
<!ATTLIST CReplaceChar
	oldChar CDATA #REQUIRED
	newChar CDATA #REQUIRED
>
<!ELEMENT CInsertChar EMPTY>
<!ATTLIST CInsertChar
	nInsertType (0|1|2|3) #REQUIRED
	nMinSpace CDATA #REQUIRED
	nMaxSpce CDATA #REQUIRED
	nCharPos CDATA #REQUIRED
	strInsert CDATA #REQUIRED
>
<!ELEMENT CLocateMethod ((vecProcessImage))>
<!ATTLIST CLocateMethod
	nLocateMethod (0|1|2|3) #REQUIRED
>
<!ELEMENT CLocateRecogUnit ((vecAnchorLocateInfo))>
<!ATTLIST CLocateRecogUnit
	bStart (0|1) #REQUIRED
	nStartIndexInChar CDATA #REQUIRED
	bEnd (0|1) #REQUIRED
	nEndIndexInChar CDATA #REQUIRED
>
<!ELEMENT CDeriveUnit ((vecFlagFind?))>
<!ATTLIST CDeriveUnit
	nIndex CDATA #REQUIRED
	nSrcRecogUnitIndex CDATA #REQUIRED
	nStartCharIndex CDATA #REQUIRED
	nEndCharIndex CDATA #REQUIRED
>

<!ELEMENT CRecogInfo ((CLocateInfo,vecKernal))>
<!ATTLIST CRecogInfo
	bMatchRegExp (0|1) #REQUIRED
	charOrder CDATA #REQUIRED
	bConfirmParams (0|1) #REQUIRED
	bIgnorePoint (0|1) #REQUIRED
	nMaxPointWidth  CDATA #REQUIRED
	nMaxPointHeight CDATA #REQUIRED
	bDetectLine (0|1) #IMPLIED 
>
<!ELEMENT positionPlus EMPTY>
<!ATTLIST positionPlus
	nBottomPlus CDATA #REQUIRED
	nLeftPlus CDATA #REQUIRED
	nRightPlus CDATA #REQUIRED
	nTopPlus CDATA #REQUIRED
>
<!ELEMENT CFlagFind EMPTY>
<!ATTLIST CFlagFind
	nFindType (0|1) #REQUIRED
	strFlag CDATA #REQUIRED
	bStart (0|1) #REQUIRED
	nStartIndex CDATA #REQUIRED
	nNum CDATA #REQUIRED
	nPosType (0|1) #REQUIRED
	nIndexPlus CDATA #REQUIRED
>
<!ELEMENT CLocateRegion ((vecProcessImage, RECT, vecAnchorLocateInfo, vecCLocateAnchor))>
<!ATTLIST CLocateRegion
	bAccurateLocate (0|1) #REQUIRED
>
<!ELEMENT CLocateLine ((RECT,RECT,CLocateInfo, positionPlus))>
<!ELEMENT CLocateInfo ((vecCLocateMethod))>
<!ATTLIST CLocateInfo
	nNumType CDATA #REQUIRED
	nMaxElementNum CDATA #REQUIRED
	nMaxHeight CDATA #REQUIRED
	nMaxSpace CDATA #REQUIRED
	nMaxWidth CDATA #REQUIRED
	nMinElementNum CDATA #REQUIRED
	nMinHeight CDATA #REQUIRED
	nMinSpace CDATA #REQUIRED
	nMinWidth CDATA #REQUIRED
	nMinWHRatio CDATA #REQUIRED
	nMaxWHRatio CDATA #REQUIRED
    nSplitWHRatio CDATA #REQUIRED
    bSplit (0|1) #REQUIRED
	bWidth (0|1) #REQUIRED
	bHeight (0|1) #REQUIRED
	bSpace (0|1) #REQUIRED
	bPostProcess (0|1) #REQUIRED
	bRemoveLineNoise (0|1) #REQUIRED
	bEraseStart (0|1) #REQUIRED
	bCheckSpace (0|1) #IMPLIED
	bAngleCorrection (0|1) #IMPLIED
	bCheckHeight (0|1) #IMPLIED
	nStandardHeight CDATA #IMPLIED 
	bInpaintLine (0|1) #IMPLIED 
	bRemoveInValidLine (0|1) #IMPLIED
	nSmooth (0|1) #IMPLIED
	
>
<!ELEMENT CRegion ((vecProcessImage?,vecImageLightType, CLocateRegion, CLocateLine?, vecLine?))>
<!ATTLIST CRegion
	nIndex CDATA #REQUIRED
	nProcessOrder CDATA #REQUIRED
	nRegionType CDATA #REQUIRED
>
<!ELEMENT CSubTemplate ((vecRegion*, vecDeriveUnit*,vecAnchor*,vecMergeUnit*,vecOutPutResult*))>
<!ATTLIST CSubTemplate
	nSubID CDATA #REQUIRED
>
<!ELEMENT RECT EMPTY>
<!ATTLIST RECT
	Bottom CDATA #REQUIRED
	Left CDATA #REQUIRED
	Right CDATA #REQUIRED
	Top CDATA #REQUIRED
>
<!ELEMENT BINARYPARAM EMPTY>
<!ATTLIST BINARYPARAM
	nBlockNum CDATA #REQUIRED
	nMethod CDATA #REQUIRED
>
<!ELEMENT CRecogUnit ((CLocateRecogUnit?, CRecogInfo?,vecCInsertChar?))>
<!ATTLIST CRecogUnit
	bLocate (0|1) #REQUIRED
	bRecog (0|1) #REQUIRED
	nIndex CDATA #REQUIRED
>

<!ATTLIST vecProcessMode
nMode (0|1) #REQUIRED>

<!ELEMENT CProcessImage ((CTrueColorToGrayEx?,CGrayToBinaryEx?,CEraseBlackBorderEx?,CTiltCorrection?,CBlurAverage?,CCropImage?,CInvertImage?,CMedianFilterEx?,CRotateEx?,CAutoCropImage?,CGaussianFilter?,CReSizeImage?,CReSizeImageEx?,CAutoRotateInTemplate?,CAutoCropInTemplate?,CHistogramEqualization?,CIDCardAutoProcess?))>
<!ATTLIST CProcessImage
	processType CDATA #REQUIRED
>

<!ELEMENT CAutoProcess
((CIDCardAutoProcessEx?,CIDCardAutoProcessEx2?,PerspectiveTransform?,PerspectiveTransformEx?,CIDCardAutoProcess?,CTrueColorToGrayEx?,CEraseBlackBorderEx?))>
<!ATTLIST CAutoProcess
	processType CDATA #REQUIRED
>

<!ELEMENT CRotateEx ((RECT))>
<!ATTLIST CRotateEx 
	nRotateType (0|1|2|3|4) #REQUIRED
>
<!ELEMENT CTiltCorrection EMPTY>
<!ATTLIST CTiltCorrection
	bSameSize (0|1) #REQUIRED
	nFilledType (0|1) #REQUIRED
	nMinAngle CDATA #REQUIRED
	nMaxAngle CDATA #REQUIRED
>
<!ELEMENT CTrueColorToGrayEx ((RECT))>
<!ATTLIST CTrueColorToGrayEx
	nFilter CDATA #REQUIRED
>
<!ELEMENT CGaussianFilter EMPTY>
<!ATTLIST CGaussianFilter
	fSigma CDATA #REQUIRED
>
<!ELEMENT CAutoRotateInTemplate EMPTY>
<!ATTLIST CAutoRotateInTemplate
	nRotateType CDATA #REQUIRED
>
<!ELEMENT CAutoCropInTemplate EMPTY>
<!ATTLIST CAutoCropInTemplate
	nCropType CDATA #REQUIRED
>
<!ELEMENT CHistogramEqualization EMPTY>
<!ATTLIST CHistogramEqualization
	nType CDATA #REQUIRED
>
<!ELEMENT CReSizeImage EMPTY>
<!ATTLIST CReSizeImage
	nWidth CDATA #REQUIRED
	nHeight CDATA #REQUIRED
>

<!ELEMENT CReSizeImageEx EMPTY>
<!ATTLIST CReSizeImageEx
	nWidth CDATA #REQUIRED
	nHeight CDATA #REQUIRED
>

<!ELEMENT CIDCardAutoProcess EMPTY>
<!ATTLIST CIDCardAutoProcess
    nCropType CDATA #REQUIRED
    nRotateType CDATA #REQUIRED
	bSameSize (0|1) #REQUIRED
	nFilledType (0|1) #REQUIRED
	nMinAngle CDATA #REQUIRED
	nMaxAngle CDATA #REQUIRED
>

<!ELEMENT CIDCardAutoProcessEx EMPTY>
<!ATTLIST CIDCardAutoProcessEx
    nCropType CDATA #REQUIRED
    bCrop CDATA #REQUIRED 
    nRotateType CDATA #REQUIRED 
    bRotate CDATA #REQUIRED 
    bTilt CDATA #REQUIRED
    bResize CDATA #REQUIRED 
	bSameSize (0|1) #REQUIRED 
	nFilledType (0|1) #REQUIRED
	nMinAngle CDATA #REQUIRED
	nMaxAngle CDATA #REQUIRED 
	nWidth CDATA #IMPLIED
	nHeight CDATA #IMPLIED 
>

<!ELEMENT CIDCardAutoProcessEx2 EMPTY>
<!ATTLIST CIDCardAutoProcessEx2
    nCropType CDATA #REQUIRED   
	nFilledType (0|1) #REQUIRED
	nMinAngle CDATA #REQUIRED
	nMaxAngle CDATA #REQUIRED
	bIs180Rotate (0|1) #REQUIRED 
	bIsValid (0|1) #REQUIRED  
	bSameSize (0|1) #REQUIRED 
	bTilt (0|1) #IMPLIED 
>

<!ELEMENT PerspectiveTransform EMPTY>
<!ATTLIST PerspectiveTransform
    nType CDATA #REQUIRED   
	nWidth CDATA #REQUIRED
	nHeight CDATA #REQUIRED 
	bIs180Rotate (0|1) #IMPLIED
	bIsValid (0|1) #IMPLIED
	nOffsetLeft CDATA #IMPLIED
	nOffsetRight CDATA #IMPLIED 
	nOffsetTop CDATA #IMPLIED 
	nOffsetBottom CDATA #IMPLIED 
>
<!ELEMENT PerspectiveTransformEx EMPTY>
<!ATTLIST PerspectiveTransformEx
    nType CDATA #REQUIRED   
	nWidth CDATA #REQUIRED
	nHeight CDATA #REQUIRED 
>

<!ELEMENT CBlurAverage EMPTY>
<!ATTLIST CBlurAverage
	nType CDATA #REQUIRED
>
<!ELEMENT vecBinaryParam ((BINARYPARAM+))>
<!ELEMENT CGrayToBinaryEx ((vecBinaryParam,RECT))>

<!ELEMENT CEraseBlackBorderEx ((RECT,RECT))>
<!ATTLIST CEraseBlackBorderEx
>
<!ELEMENT CInvertImage ((RECT))>
<!ATTLIST CInvertImage
>
<!ELEMENT CMedianFilterEx ((RECT))>
<!ATTLIST CMedianFilterEx
>
<!ELEMENT CAutoCropImage ((RECT))>
<!ATTLIST CAutoCropImage
>
<!ELEMENT CLine ((RECT?,CReconvertInfo?,CRecogInfo?, vecRecogUnit?, vecLineKeyWord?, vecCLocateAnchor?))>
<!ATTLIST CLine
	bEndOffset (0|1) #REQUIRED
	bStartOffset (0|1) #REQUIRED
	nIndex CDATA #REQUIRED
	bExist (0|1) #REQUIRED
	bNeedRecog (0|1) #REQUIRED
	nCheckKeyWord CDATA #REQUIRED
>
<!ELEMENT CReconvertInfo EMPTY>
<!ATTLIST CReconvertInfo
    nPosX CDATA #REQUIRED
    nPosY CDATA #REQUIRED
    nCharWidth CDATA #REQUIRED
    nCharHeight CDATA #REQUIRED
    nWHRatio CDATA #REQUIRED
    strContent CDATA #REQUIRED
    nThreshold CDATA #REQUIRED 
>
<!ELEMENT LIGHTTYPE (#PCDATA)>
<!ELEMENT CKeyWord ((vecCLocateAnchor))>
<!ATTLIST CKeyWord
	nConfirmType (0|1|2|3) #REQUIRED
	content CDATA #REQUIRED
	nMinWidth CDATA #REQUIRED
	nMaxWidth CDATA #REQUIRED
	nMinHeight CDATA #REQUIRED
	nMaxHeight CDATA #REQUIRED
>
<!ELEMENT IDCARD ((vecProcessImage?,CIDCardTemplate*,TemplatePath*))>

<!ELEMENT CIDCardTemplate ((vecAutoProcess?, vecProcessImage, vecRegion, vecDeriveUnit*,vecAnchor,vecOutPutResult,vecMergeUnit?,vecSubTemplate?))>
<!ATTLIST CIDCardTemplate
	chDocumentName CDATA #REQUIRED
	imageSizeType (0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|18|21) #REQUIRED
	nMainDocumentID CDATA #REQUIRED
	engDocumentName CDATA #IMPLIED
>
<!ELEMENT TemplatePath (#PCDATA)>
<!ELEMENT CAnchor EMPTY>
<!ATTLIST CAnchor
	anchorPos CDATA #REQUIRED
	nMinPos CDATA #REQUIRED
	nMaxPos CDATA #REQUIRED
	anchorType (0|1|2|3|4|5|6) #REQUIRED
	bEnable (0|1) #REQUIRED
	nIndex CDATA #REQUIRED
	bInherited (0|1) #IMPLIED
>
<!ELEMENT CLocateAnchor EMPTY>
<!ATTLIST CLocateAnchor
	nDisToAnchor CDATA #REQUIRED
	nAnchorIndex CDATA #REQUIRED
	anchorType (0|1|2|3|4|5|6) #REQUIRED
>
<!ELEMENT CAnchorLocateInfo EMPTY>
<!ATTLIST CAnchorLocateInfo
	nAnchorIndex CDATA #REQUIRED
	nDisToAnchor CDATA #REQUIRED
	anchorType (0|1|2|3|4) #REQUIRED
>
<!ELEMENT CKernalInfo ((vecCharRatio))>
<!ATTLIST CKernalInfo
	kernalMainType (1|2|3) #REQUIRED
	strFilterPlus CDATA ""
	nFillingMethod CDATA ""
	nFilterType CDATA ""
	nRecogImgeType (0|1) #REQUIRED
	nKernalSubType CDATA #REQUIRED
	nRecogType (0|1) #REQUIRED
>
<!ELEMENT CCharRatio EMPTY>
<!ATTLIST CCharRatio
	charType (0|1|2|3|4|10) #REQUIRED
	nWHRatio CDATA #REQUIRED
	strChars CDATA #REQUIRED
>
<!ELEMENT CCropImage ((RECT))>
<!ATTLIST CCropImage
	nMinSrcWidth CDATA #REQUIRED
	nMinSrcHeight CDATA #REQUIRED
	nUnitType (0|1) #REQUIRED
	nRotateType CDATA #REQUIRED
>

=== 17719543022/BoardingControl_Linux/SDK/bin/3rdSo/ChinaSafe/IDCARDS/35.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE IDCARD SYSTEM "IDCARD.dtd">
<IDCARD>
	<CIDCardTemplate nMainDocumentID="35" chDocumentName="台湾地区居留证-照片页" engDocumentName="China Taiwan Area Resident Permit Portrait Page" imageSizeType="2">
		<vecProcessImage>
			<CProcessImage processType="3">
				<CEraseBlackBorderEx>
					<!--processRect要检测黑边的区域-->
					<RECT Left="0" Top="0" Right="10000" Bottom="10000" />
					<RECT Left="2000" Top="2000" Right="8900" Bottom="8000" />
				</CEraseBlackBorderEx>
			</CProcessImage>
		</vecProcessImage>
		<vecRegion>
			<!--CRegion:区域信息
				nIndex:区域编号
				nRegionType:区域类型,0代表头像区域,1代表识别区域
				nProcessOrder:该区域被处理的顺序
				rcPosition 坐标均为占整张图像的百分比*10000
			-->
			<CRegion nIndex="0" nRegionType="0" nProcessOrder="0">
				<!--处理该区域需要的图像信息的光的类型-->
				<vecImageLightType>
					<!--1:可见光图;2:红外光图;4:紫外光图 -->
					<LIGHTTYPE>1</LIGHTTYPE>
					<LIGHTTYPE>2</LIGHTTYPE>
				</vecImageLightType>
				<!--定义区域的定位信息,如果是头像区域还需要进一步精确定位，识别区域就不用了-->
				<!--bAccurateLocate为1表示需要进一步精确定位,0代表不需要-->
				<CLocateRegion bAccurateLocate="1">
					<!--在定位前进行的预处理信息，一般是二值化-->
					<vecProcessImage>
						<CProcessImage processType="1">
							<CTrueColorToGrayEx nFilter="0">
								<RECT Top="0" Right="0" Bottom="0" Left="0" />
							</CTrueColorToGrayEx>
						</CProcessImage>
					</vecProcessImage>
					<!--rcMinRect:指定定位区域的最小范围，即定位后的区域范围必须包含这个区域-->
					<RECT Left="7000" Top="3600" Right="9600" Bottom="8000" />
					<vecAnchorLocateInfo>
						<!--nDisToAnchor的值也是整图的百分比*10000计算出来的-->
						<CAnchorLocateInfo nAnchorIndex="0" nDisToAnchor="6800" anchorType="1" />
						<CAnchorLocateInfo nAnchorIndex="0" nDisToAnchor="9900" anchorType="2" />
						<CAnchorLocateInfo nAnchorIndex="0" nDisToAnchor="3400" anchorType="3" />
						<CAnchorLocateInfo nAnchorIndex="0" nDisToAnchor="9000" anchorType="4" />
					</vecAnchorLocateInfo>
					<!--该区域定义的区域类型基准点的信息-->
					<vecCLocateAnchor>
						<CLocateAnchor nDisToAnchor="0" nAnchorIndex="1" anchorType="1" />
					</vecCLocateAnchor>
				</CLocateRegion>
				<!--区域内定位行的信息-->
			</CRegion>

		</vecRegion>
		<vecDeriveUnit>
		</vecDeriveUnit>
		<!--vecAnchor:该证件的所有的基准点的信息-->
		<!--anchorType:基准点类型，取值如下
			ZEROANCHOR=0,//(0,0)基准
			LEFT=1,//左边
			RIGHT=2,//右边
			TOP=3,//上边
			BOTTOM=4,//下边 櫺建省
		-->
		<vecAnchor>
			<!--0基准点-->
			<CAnchor nIndex="0" anchorType="0" anchorPos="0" bEnable="0" nMinPos="-1" nMaxPos="-1" />
			<!--头像区域定义左基准-->
			<CAnchor nIndex="1" anchorPos="-1" anchorType="1" bEnable="0" nMinPos="-1" nMaxPos="-1" />
			<!--头像区域定义下基准-->

		</vecAnchor>
		<vecOutPutResult>
			<COutPutResult nIndex="0" cellRecogType="20" cellName="保留" cellNameEng="Reserve" nOutputThreshold="0" nOutputNumber="0" bFormatResult="0" />
		</vecOutPutResult>
	</CIDCardTemplate>
</IDCARD>

=== 17719543022/BoardingControl_Linux/SDK/bin/3rdSo/ChinaSafe/IDCARDS/1010.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE IDCARD SYSTEM "IDCARD.dtd">
<IDCARD>
	<CIDCardTemplate nMainDocumentID="1010" chDocumentName="名片" engDocumentName="Business Card" imageSizeType="2">
		<vecProcessImage>
		</vecProcessImage>
		<vecRegion>
		</vecRegion>
		<vecDeriveUnit>
		</vecDeriveUnit>
		<vecAnchor>
		</vecAnchor>
		<vecOutPutResult>
			<COutPutResult nIndex="0" cellRecogType="20" cellNameEng="Reserve" cellName="保留" nOutputThreshold="0" nOutputNumber="0" bFormatResult="0" />
			<COutPutResult nIndex="1" cellRecogType="0" cellNameEng="Name" cellName="姓名" nOutputThreshold="0" nOutputNumber="0" bFormatResult="0" />
			<COutPutResult nIndex="2" cellRecogType="20" cellNameEng="Unit name" cellName="单位名称" nOutputThreshold="0" nOutputNumber="0" bFormatResult="0" />
			<COutPutResult nIndex="3" cellRecogType="20" cellNameEng="Post" cellName="职务" nOutputThreshold="0" nOutputNumber="0" bFormatResult="0" />
			<COutPutResult nIndex="4" cellRecogType="20" cellNameEng="Mobile phone" cellName="手机" nOutputThreshold="0" nOutputNumber="0" bFormatResult="0"/> 
			<COutPutResult nIndex="5" cellRecogType="20" cellNameEng="Telephone" cellName="电话" nOutputThreshold="0" nOutputNumber="0" bFormatResult="0" />
			<COutPutResult nIndex="6" cellRecogType="20" cellNameEng="E-mail" cellName="电子邮件" nOutputThreshold="0" nOutputNumber="0" bFormatResult="0" />
			<COutPutResult nIndex="7" cellRecogType="20" cellNameEng="Company homepage" cellName="公司主页" nOutputThreshold="0" nOutputNumber="0" bFormatResult="0"/>
			<COutPutResult nIndex="8" cellRecogType="20" cellNameEng="Postal address" cellName="通讯地址" nOutputThreshold="0" nOutputNumber="0" bFormatResult="0"/> 
			<COutPutResult nIndex="9" cellRecogType="20" cellNameEng="Postal Code" cellName="邮政编码" nOutputThreshold="0" nOutputNumber="0" bFormatResult="0"/> 
			<COutPutResult nIndex="10" cellRecogType="20" cellNameEng="Fax" cellName="传真" nOutputThreshold="0" nOutputNumber="0" bFormatResult="0"/> 
			<COutPutResult nIndex="11" cellRecogType="20" cellNameEng="Pager" cellName="呼机" nOutputThreshold="0" nOutputNumber="0" bFormatResult="0"/> 
			<COutPutResult nIndex="12" cellRecogType="20" cellNameEng="Remarks" cellName="备注" nOutputThreshold="0" nOutputNumber="0" bFormatResult="0"/>

		</vecOutPutResult>
	</CIDCardTemplate>

</IDCARD>

=== 17719543022/BoardingControl_Linux/SDK/bin/3rdSo/ChinaSafe/IDCARDS.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE IDCARD SYSTEM "IDCARD.dtd">
<IDCARD>
<!--全局的图像预处理-->
  <vecProcessImage>
    <CProcessImage processType="8" nEnable="1">
      <CTiltCorrection nMaxAngle="0.3" bSameSize="1" nMinAngle="0.017" nFilledType="0" />
    </CProcessImage>
  </vecProcessImage>
  <!--通用机读证件-->
  <TemplatePath>IDCARDS/13.xml</TemplatePath><!--护照-->
  <TemplatePath>IDCARDS/12.xml</TemplatePath><!--签证-->
  <TemplatePath>IDCARDS/2009.xml</TemplatePath><!--TD-1型机读旅行证件-->
  <TemplatePath>IDCARDS/2006.xml</TemplatePath><!--TD-2型机读旅行证件-->
  <!--中国大陆-->
<TemplatePath>IDCARDS/2.xml</TemplatePath><!--居民身份证-照片页-->
<TemplatePath>IDCARDS/3.xml</TemplatePath><!--居民身份证-签发机关页-->
<TemplatePath>IDCARDS/4.xml</TemplatePath><!--临时居民身份证-->
<TemplatePath>IDCARDS/5.xml</TemplatePath><!--机动车驾驶证-->
<TemplatePath>IDCARDS/6.xml</TemplatePath><!--机动车行驶证-->
<TemplatePath>IDCARDS/30.xml</TemplatePath><!--机动车行驶证副页-->
<TemplatePath>IDCARDS/9.xml</TemplatePath><!--往来港澳通行证2005版-照片页-->
<TemplatePath>IDCARDS/22.xml</TemplatePath><!--往来港澳通行证2014版-照片页-->
<TemplatePath>IDCARDS/11.xml</TemplatePath><!--往来台湾通行证1992版-照片页-->
<TemplatePath>IDCARDS/29.xml</TemplatePath><!--往来台湾通行证2017版-照片页-->
<TemplatePath>IDCARDS/14.xml</TemplatePath><!--港澳居民来往内地通行证-照片页-->
<TemplatePath>IDCARDS/15.xml</TemplatePath><!--港澳居民来往内地通行证-机读码页-->
<TemplatePath>IDCARDS/10.xml</TemplatePath><!--台湾居民来往大陆通行证1992版-照片页-->
<TemplatePath>IDCARDS/25.xml</TemplatePath><!--台湾居民来往大陆通行证2015版-照片页-->
<TemplatePath>IDCARDS/26.xml</TemplatePath><!--台湾居民来往大陆通行证2015版-机读码页-->
<TemplatePath>IDCARDS/31.xml</TemplatePath><!--中华人民共和国港澳居民居住证——照片页-->
<TemplatePath>IDCARDS/32.xml</TemplatePath><!--中华人民共和国港澳居民居住证——签发机关页-->
<TemplatePath>IDCARDS/33.xml</TemplatePath><!--外国人永久居留身份证——照片页-->
<TemplatePath>IDCARDS/23.xml</TemplatePath><!--边境地区出入境通行证2014版-照片页-->
<TemplatePath>IDCARDS/1003.xml</TemplatePath><!--边境地区出入境通行证2005版-照片页-->
<TemplatePath>IDCARDS/1004.xml</TemplatePath><!--边境地区出入境通行证2005版-信息页-->
<TemplatePath>IDCARDS/16.xml</TemplatePath><!--常住人口登记卡-->
<TemplatePath>IDCARDS/1009.xml</TemplatePath>
<TemplatePath>IDCARDS/1010.xml</TemplatePath><!--名片-->
<TemplatePath>IDCARDS/1000.xml</TemplatePath><!--居住证（广东、广西、东莞）-照片页-->
<TemplatePath>IDCARDS/1013.xml</TemplatePath><!--深圳经济特区居住证2015版-照片页-->
<TemplatePath>IDCARDS/1021.xml</TemplatePath><!--社会保障卡（北京、重庆）-照片页-->
<TemplatePath>IDCARDS/1039.xml</TemplatePath><!--厦门市社会保障卡-照片页-->
<TemplatePath>IDCARDS/1007.xml</TemplatePath><!--律师执业证-签发机关页-->
<TemplatePath>IDCARDS/1008.xml</TemplatePath><!--律师执业证-照片页-->
<TemplatePath>IDCARDS/8.xml</TemplatePath><!--士兵证1998版-->
<TemplatePath>IDCARDS/7.xml</TemplatePath><!--军官证1998版-->
<TemplatePath>IDCARDS/18.xml</TemplatePath><!--军官证1998版-照片页-->
<TemplatePath>IDCARDS/19.xml</TemplatePath><!--军官证1998版-信息页-->
<TemplatePath>IDCARDS/20.xml</TemplatePath><!--警官证2006版-照片页-->
<TemplatePath>IDCARDS/21.xml</TemplatePath><!--警官证2006版-信息页-->
<TemplatePath>IDCARDS/24.xml</TemplatePath><!--中国人民解放军车辆驾驶证2010版-->
<TemplatePath>IDCARDS/27.xml</TemplatePath><!--中国人民解放军行车执照2012版-->
<TemplatePath>IDCARDS/17.xml</TemplatePath><!--海员证2009版-照片页-->
<TemplatePath>IDCARDS/1017.xml</TemplatePath><!--临时海员证-->
<TemplatePath>IDCARDS/1018.xml</TemplatePath><!--内蒙古自治区人民法院工作证-->
<TemplatePath>IDCARDS/1019.xml</TemplatePath><!--内蒙古自治区检察机关工作证-->
<TemplatePath>IDCARDS/1037.xml</TemplatePath><!--神煤集团工作证-->
<TemplatePath>IDCARDS/1009.xml</TemplatePath><!--中华人民共和国道路运输证IC卡-->

<!--港奥台证件-->
<TemplatePath>IDCARDS/34.xml</TemplatePath><!--台湾地区（金马澎）入出境许可证2015版-照片页-->
<TemplatePath>IDCARDS/35.xml</TemplatePath><!--台湾居留证-->
<TemplatePath>IDCARDS/1001.xml</TemplatePath><!--香港居民身份证2003版-照片页-->
<TemplatePath>IDCARDS/1005.xml</TemplatePath><!--澳门居民身份证-照片页-->
<TemplatePath>IDCARDS/1031.xml</TemplatePath><!--台湾地区身份证-照片页-->
<TemplatePath>IDCARDS/1032.xml</TemplatePath><!--台湾地区身份证-条码页-->
<TemplatePath>IDCARDS/1030.xml</TemplatePath><!--台湾全民健康保险卡-->
<TemplatePath>IDCARDS/1040.xml</TemplatePath><!--台湾地区驾驶证-->
<!--印度尼西亚-->
<TemplatePath>IDCARDS/2010.xml</TemplatePath><!--印度尼西亚居民身份证-->
<TemplatePath>IDCARDS/2041.xml</TemplatePath>
<!--日本-->
<TemplatePath>IDCARDS/2051.xml</TemplatePath><!--日本驾驶证-->
<!--马来西亚-->
<TemplatePath>IDCARDS/2001.xml</TemplatePath><!--马来西亚身份证-照片页-->
<TemplatePath>IDCARDS/2021.xml</TemplatePath><!--马拉西亚驾驶证-->
<!--墨西哥-->
<TemplatePath>IDCARDS/2013.xml</TemplatePath><!--墨西哥选民证-照片页-->
<TemplatePath>IDCARDS/2014.xml</TemplatePath><!--墨西哥选民证-机读码页-->
<!--新西兰-->
<TemplatePath>IDCARDS/2003.xml</TemplatePath><!--新西兰驾驶证-->
<!--新加坡-->
<TemplatePath>IDCARDS/2004.xml</TemplatePath><!--新加坡身份证-->
<TemplatePath>IDCARDS/2031.xml</TemplatePath><!--新加坡驾驶证-->
<!--瑞典-->
<TemplatePath>IDCARDS/2020.xml</TemplatePath><!--瑞典驾驶证-->
<!--泰国-->
<TemplatePath>IDCARDS/2011.xml</TemplatePath><!--泰国国民身份证-->
<TemplatePath>IDCARDS/2012.xml</TemplatePath><!--泰国驾驶证-->
<!--美国-->
<TemplatePath>IDCARDS/2002.xml</TemplatePath><!--美国加利福利亚驾驶证-->
<!--越南-->
<TemplatePath>IDCARDS/36.xml</TemplatePath><!--越南出入境通行证-->
</IDCARD>
